# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - tonkatsu2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'tonkatsu2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_eb9b451fa37041a18b61f27ec801ca98 }}
        package: .
        
    - name: npm audit action
      uses: oke-py/npm-audit-action@v1.5.0
      with:
        # GitHub access token used to create an issue
        github_token: f727fcfbd1a44cb033a3eafecb9d5ae04c2c0ed6
